var paths = {};

var Path = require('path');

paths.base = Path.normalize(__dirname);

function Grunt(grunt) {
	var tasks = [
		'grunt-6to5',
		'grunt-add-comment',
		'grunt-contrib-uglify'
	];

	for (var i = 0; i < tasks.length; i++)
		grunt.loadNpmTasks(tasks[i]);

	require('time-grunt')(grunt);

	var pathOption = getPathOption(grunt);

	Configuration = {};
	Configuration.package = grunt.file.readJSON('package.json');

	Configuration['6to5'] = {
		options: {
			sourceMap: false
		},
		dist: {
			files: [{
				expand: true,
				cwd: paths.base,
				ext: '.js',
				src: (pathOption ? pathOption.name : ['src/**/*.es6']),
				dest: paths.base
			}]
		}
	};

	Configuration.add_comment = {
		common: {
			options: {
				comments: ['Autogenerated, do not edit. All changes will be undone.'],
				prepend: true,
				syntaxes: {
					'.js': '//'
				}
			},
			files: [{
				expand: true,
				src: (pathOption ? [pathOption.name.replace('.es6', '.js')] : ['lib/**/*.js']),
			}]
		},
		dist: {
			options: {
				comments: [
				Configuration.package.name,
				'version: ' + Configuration.package.version,
				'author: ' + Configuration.package.author,
				'generated: ' + new Date(), 
				'Autogenerated, do not edit. All changes will be undone.'], 
				prepend: true,
				syntaxes: {
					'.js': '//'
				}
			},
			files: [{
				expand: true,
				src: ['dist/*.js'],
			}]
		}
	};

	Configuration.uglify = {
		options: {
			mangle: {
				except: ['angular']
			}
		},
		dist: {
			files: {
				'dist/angular-property-binder.min.js': ['src/core.js', 'src/providers/binder.js', 'src/services/binder.js']
			}
		}
	}

	grunt.initConfig(Configuration);

	grunt.registerTask('es6', ['6to5:dist', 'add_comment:common']);
	grunt.registerTask('build', ['6to5:dist', 'uglify:dist', 'add_comment:dist']);
};

module.exports = Grunt;

function getPathOption(grunt) {
	var pathOption = false;

	if (grunt.option('path')) {

		pathOption = {};
		pathOption.name = Path.normalize(grunt.option('path')).replace(paths.base, '').slice(1);
		pathOption.extension = Path.extname(grunt.option('path'));
	}

	return pathOption;
}